services:
  web:
    build: ./app
    command: gunicorn --bind 0.0.0.0:8000 netology_pd_diplom.wsgi
    volumes:
      - ./app:/app
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - app/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:6-alpine

  celery:
    build: ./app
    command: celery -A netology_pd_diplom worker -l info
    volumes:
      - ./app:/app
    env_file:
      - app/.env
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./app
    command: celery -A netology_pd_diplom beat -l info
    volumes:
      - ./app:/app
    env_file:
      - app/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
