services:
  web:
    build: ./app
    command: gunicorn --bind 0.0.0.0:8000 netology_pd_diplom.wsgi
    volumes:
      - ./app:/app
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - app/.env
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - app/.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: